
#run_folder: wandb/wandb_cluster/run-20250306_142016-5ru26uv5/

config_location_in_run_folder: /files/config.yaml

checkpoint_dirs_location_in_run_folder: /files

weight_file_regex: '^model_epoch_([0-9]+)\.pth$'

num_trajectories: 50

to_change:
  agent_config:
    sampler_config:
      _target_: movement_primitive_diffusion.samplers.euler.EulerSampler
    diffusion_steps: 35

# Set what should be used to determine if model performance increased in testing in environment
performance_metric: reward #success_rate # can be anything that is returned in the dict of workspace.test_agent(agent)
performance_direction: max # {min, max}


wandb:
  entity: johannes-pfeil-karlsruhe-institute-of-technology # wandb-user
  project: lamp
  group: movement-primitive-diffusion-experiment
  mode: online # online, offline, disabled