
config: wandb/run-20250218_180505-410af9u9/files/config.yaml
checkpoint_dir: wandb/run-20250218_180505-410af9u9/files
# For example:
# config: model_checkpoints/run-id/config.yaml
# checkpoint_dir: model_checkpoints/run-id/

# current best
# run-20250218_180505-410af9u9

weight_file_regex: '^model_epoch_([0-9]+)\.pth$'

num_trajectories: 10

to_change:
  agent_config:
    sampler_config:
      _target_: movement_primitive_diffusion.samplers.euler.EulerSampler
    diffusion_steps: 35

# Set what should be used to determine if model performance increased in testing in environment
performance_metric: sucess_rate_grabbed_hood #success_rate # can be anything that is returned in the dict of workspace.test_agent(agent)
performance_direction: max # {min, max}


wandb:
  entity: johannes-pfeil-karlsruhe-institute-of-technology # wandb-user
  project: lamp
  group: movement-primitive-diffusion-experiment
  mode: online # online, offline, disabled